// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

#ifndef PROTOBUF_Packet_2eproto__INCLUDED
#define PROTOBUF_Packet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_Packet_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPacketVersionImpl();
void InitDefaultsPacketVersion();
void InitDefaultsRequestPacketPb_ContextEntry_DoNotUseImpl();
void InitDefaultsRequestPacketPb_ContextEntry_DoNotUse();
void InitDefaultsRequestPacketPb_StatusEntry_DoNotUseImpl();
void InitDefaultsRequestPacketPb_StatusEntry_DoNotUse();
void InitDefaultsRequestPacketPbImpl();
void InitDefaultsRequestPacketPb();
void InitDefaultsResponsePacketPb_StatusEntry_DoNotUseImpl();
void InitDefaultsResponsePacketPb_StatusEntry_DoNotUse();
void InitDefaultsResponsePacketPbImpl();
void InitDefaultsResponsePacketPb();
inline void InitDefaults() {
  InitDefaultsPacketVersion();
  InitDefaultsRequestPacketPb_ContextEntry_DoNotUse();
  InitDefaultsRequestPacketPb_StatusEntry_DoNotUse();
  InitDefaultsRequestPacketPb();
  InitDefaultsResponsePacketPb_StatusEntry_DoNotUse();
  InitDefaultsResponsePacketPb();
}
}  // namespace protobuf_Packet_2eproto
class PacketVersion;
class PacketVersionDefaultTypeInternal;
extern PacketVersionDefaultTypeInternal _PacketVersion_default_instance_;
class RequestPacketPb;
class RequestPacketPbDefaultTypeInternal;
extern RequestPacketPbDefaultTypeInternal _RequestPacketPb_default_instance_;
class RequestPacketPb_ContextEntry_DoNotUse;
class RequestPacketPb_ContextEntry_DoNotUseDefaultTypeInternal;
extern RequestPacketPb_ContextEntry_DoNotUseDefaultTypeInternal _RequestPacketPb_ContextEntry_DoNotUse_default_instance_;
class RequestPacketPb_StatusEntry_DoNotUse;
class RequestPacketPb_StatusEntry_DoNotUseDefaultTypeInternal;
extern RequestPacketPb_StatusEntry_DoNotUseDefaultTypeInternal _RequestPacketPb_StatusEntry_DoNotUse_default_instance_;
class ResponsePacketPb;
class ResponsePacketPbDefaultTypeInternal;
extern ResponsePacketPbDefaultTypeInternal _ResponsePacketPb_default_instance_;
class ResponsePacketPb_StatusEntry_DoNotUse;
class ResponsePacketPb_StatusEntry_DoNotUseDefaultTypeInternal;
extern ResponsePacketPb_StatusEntry_DoNotUseDefaultTypeInternal _ResponsePacketPb_StatusEntry_DoNotUse_default_instance_;

enum PacketVersion_Version {
  PacketVersion_Version_NO_VERSION = 0,
  PacketVersion_Version_V1_VERSION = 1,
  PacketVersion_Version_MAX_VERSION = 10000,
  PacketVersion_Version_PacketVersion_Version_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PacketVersion_Version_PacketVersion_Version_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PacketVersion_Version_IsValid(int value);
const PacketVersion_Version PacketVersion_Version_Version_MIN = PacketVersion_Version_NO_VERSION;
const PacketVersion_Version PacketVersion_Version_Version_MAX = PacketVersion_Version_MAX_VERSION;
const int PacketVersion_Version_Version_ARRAYSIZE = PacketVersion_Version_Version_MAX + 1;

const ::google::protobuf::EnumDescriptor* PacketVersion_Version_descriptor();
inline const ::std::string& PacketVersion_Version_Name(PacketVersion_Version value) {
  return ::google::protobuf::internal::NameOfEnum(
    PacketVersion_Version_descriptor(), value);
}
inline bool PacketVersion_Version_Parse(
    const ::std::string& name, PacketVersion_Version* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketVersion_Version>(
    PacketVersion_Version_descriptor(), name, value);
}
// ===================================================================

class PacketVersion : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PacketVersion) */ {
 public:
  PacketVersion();
  virtual ~PacketVersion();

  PacketVersion(const PacketVersion& from);

  inline PacketVersion& operator=(const PacketVersion& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PacketVersion(PacketVersion&& from) noexcept
    : PacketVersion() {
    *this = ::std::move(from);
  }

  inline PacketVersion& operator=(PacketVersion&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacketVersion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PacketVersion* internal_default_instance() {
    return reinterpret_cast<const PacketVersion*>(
               &_PacketVersion_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PacketVersion* other);
  friend void swap(PacketVersion& a, PacketVersion& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PacketVersion* New() const PROTOBUF_FINAL { return New(NULL); }

  PacketVersion* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PacketVersion& from);
  void MergeFrom(const PacketVersion& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PacketVersion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef PacketVersion_Version Version;
  static const Version NO_VERSION =
    PacketVersion_Version_NO_VERSION;
  static const Version V1_VERSION =
    PacketVersion_Version_V1_VERSION;
  static const Version MAX_VERSION =
    PacketVersion_Version_MAX_VERSION;
  static inline bool Version_IsValid(int value) {
    return PacketVersion_Version_IsValid(value);
  }
  static const Version Version_MIN =
    PacketVersion_Version_Version_MIN;
  static const Version Version_MAX =
    PacketVersion_Version_Version_MAX;
  static const int Version_ARRAYSIZE =
    PacketVersion_Version_Version_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Version_descriptor() {
    return PacketVersion_Version_descriptor();
  }
  static inline const ::std::string& Version_Name(Version value) {
    return PacketVersion_Version_Name(value);
  }
  static inline bool Version_Parse(const ::std::string& name,
      Version* value) {
    return PacketVersion_Version_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PacketVersion)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_Packet_2eproto::TableStruct;
  friend void ::protobuf_Packet_2eproto::InitDefaultsPacketVersionImpl();
};
// -------------------------------------------------------------------

class RequestPacketPb_ContextEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<RequestPacketPb_ContextEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<RequestPacketPb_ContextEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  RequestPacketPb_ContextEntry_DoNotUse();
  RequestPacketPb_ContextEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const RequestPacketPb_ContextEntry_DoNotUse& other);
  static const RequestPacketPb_ContextEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const RequestPacketPb_ContextEntry_DoNotUse*>(&_RequestPacketPb_ContextEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class RequestPacketPb_StatusEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<RequestPacketPb_StatusEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<RequestPacketPb_StatusEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  RequestPacketPb_StatusEntry_DoNotUse();
  RequestPacketPb_StatusEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const RequestPacketPb_StatusEntry_DoNotUse& other);
  static const RequestPacketPb_StatusEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const RequestPacketPb_StatusEntry_DoNotUse*>(&_RequestPacketPb_StatusEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class RequestPacketPb : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RequestPacketPb) */ {
 public:
  RequestPacketPb();
  virtual ~RequestPacketPb();

  RequestPacketPb(const RequestPacketPb& from);

  inline RequestPacketPb& operator=(const RequestPacketPb& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RequestPacketPb(RequestPacketPb&& from) noexcept
    : RequestPacketPb() {
    *this = ::std::move(from);
  }

  inline RequestPacketPb& operator=(RequestPacketPb&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestPacketPb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestPacketPb* internal_default_instance() {
    return reinterpret_cast<const RequestPacketPb*>(
               &_RequestPacketPb_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(RequestPacketPb* other);
  friend void swap(RequestPacketPb& a, RequestPacketPb& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RequestPacketPb* New() const PROTOBUF_FINAL { return New(NULL); }

  RequestPacketPb* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RequestPacketPb& from);
  void MergeFrom(const RequestPacketPb& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RequestPacketPb* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> context = 6;
  int context_size() const;
  void clear_context();
  static const int kContextFieldNumber = 6;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      context() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_context();

  // map<string, string> status = 7;
  int status_size() const;
  void clear_status();
  static const int kStatusFieldNumber = 7;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      status() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_status();

  // string sequence = 2;
  void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  const ::std::string& sequence() const;
  void set_sequence(const ::std::string& value);
  #if LANG_CXX11
  void set_sequence(::std::string&& value);
  #endif
  void set_sequence(const char* value);
  void set_sequence(const char* value, size_t size);
  ::std::string* mutable_sequence();
  ::std::string* release_sequence();
  void set_allocated_sequence(::std::string* sequence);

  // bytes buffer = 5;
  void clear_buffer();
  static const int kBufferFieldNumber = 5;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  #if LANG_CXX11
  void set_buffer(::std::string&& value);
  #endif
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // int32 version = 1;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::google::protobuf::int32 version() const;
  void set_version(::google::protobuf::int32 value);

  // int32 cmd = 3;
  void clear_cmd();
  static const int kCmdFieldNumber = 3;
  ::google::protobuf::int32 cmd() const;
  void set_cmd(::google::protobuf::int32 value);

  // int32 subcmd = 4;
  void clear_subcmd();
  static const int kSubcmdFieldNumber = 4;
  ::google::protobuf::int32 subcmd() const;
  void set_subcmd(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RequestPacketPb)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      RequestPacketPb_ContextEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > context_;
  ::google::protobuf::internal::MapField<
      RequestPacketPb_StatusEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > status_;
  ::google::protobuf::internal::ArenaStringPtr sequence_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  ::google::protobuf::int32 version_;
  ::google::protobuf::int32 cmd_;
  ::google::protobuf::int32 subcmd_;
  mutable int _cached_size_;
  friend struct ::protobuf_Packet_2eproto::TableStruct;
  friend void ::protobuf_Packet_2eproto::InitDefaultsRequestPacketPbImpl();
};
// -------------------------------------------------------------------

class ResponsePacketPb_StatusEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ResponsePacketPb_StatusEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<ResponsePacketPb_StatusEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  ResponsePacketPb_StatusEntry_DoNotUse();
  ResponsePacketPb_StatusEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ResponsePacketPb_StatusEntry_DoNotUse& other);
  static const ResponsePacketPb_StatusEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ResponsePacketPb_StatusEntry_DoNotUse*>(&_ResponsePacketPb_StatusEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ResponsePacketPb : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ResponsePacketPb) */ {
 public:
  ResponsePacketPb();
  virtual ~ResponsePacketPb();

  ResponsePacketPb(const ResponsePacketPb& from);

  inline ResponsePacketPb& operator=(const ResponsePacketPb& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResponsePacketPb(ResponsePacketPb&& from) noexcept
    : ResponsePacketPb() {
    *this = ::std::move(from);
  }

  inline ResponsePacketPb& operator=(ResponsePacketPb&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponsePacketPb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponsePacketPb* internal_default_instance() {
    return reinterpret_cast<const ResponsePacketPb*>(
               &_ResponsePacketPb_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ResponsePacketPb* other);
  friend void swap(ResponsePacketPb& a, ResponsePacketPb& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResponsePacketPb* New() const PROTOBUF_FINAL { return New(NULL); }

  ResponsePacketPb* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResponsePacketPb& from);
  void MergeFrom(const ResponsePacketPb& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResponsePacketPb* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> status = 5;
  int status_size() const;
  void clear_status();
  static const int kStatusFieldNumber = 5;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      status() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_status();

  // string sequence = 2;
  void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  const ::std::string& sequence() const;
  void set_sequence(const ::std::string& value);
  #if LANG_CXX11
  void set_sequence(::std::string&& value);
  #endif
  void set_sequence(const char* value);
  void set_sequence(const char* value, size_t size);
  ::std::string* mutable_sequence();
  ::std::string* release_sequence();
  void set_allocated_sequence(::std::string* sequence);

  // bytes buffer = 4;
  void clear_buffer();
  static const int kBufferFieldNumber = 4;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  #if LANG_CXX11
  void set_buffer(::std::string&& value);
  #endif
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // string msg = 6;
  void clear_msg();
  static const int kMsgFieldNumber = 6;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 version = 1;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::google::protobuf::int32 version() const;
  void set_version(::google::protobuf::int32 value);

  // int32 result = 3;
  void clear_result();
  static const int kResultFieldNumber = 3;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ResponsePacketPb)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      ResponsePacketPb_StatusEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > status_;
  ::google::protobuf::internal::ArenaStringPtr sequence_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 version_;
  ::google::protobuf::int32 result_;
  mutable int _cached_size_;
  friend struct ::protobuf_Packet_2eproto::TableStruct;
  friend void ::protobuf_Packet_2eproto::InitDefaultsResponsePacketPbImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PacketVersion

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RequestPacketPb

// int32 version = 1;
inline void RequestPacketPb::clear_version() {
  version_ = 0;
}
inline ::google::protobuf::int32 RequestPacketPb::version() const {
  // @@protoc_insertion_point(field_get:RequestPacketPb.version)
  return version_;
}
inline void RequestPacketPb::set_version(::google::protobuf::int32 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:RequestPacketPb.version)
}

// string sequence = 2;
inline void RequestPacketPb::clear_sequence() {
  sequence_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RequestPacketPb::sequence() const {
  // @@protoc_insertion_point(field_get:RequestPacketPb.sequence)
  return sequence_.GetNoArena();
}
inline void RequestPacketPb::set_sequence(const ::std::string& value) {
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RequestPacketPb.sequence)
}
#if LANG_CXX11
inline void RequestPacketPb::set_sequence(::std::string&& value) {
  
  sequence_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RequestPacketPb.sequence)
}
#endif
inline void RequestPacketPb::set_sequence(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RequestPacketPb.sequence)
}
inline void RequestPacketPb::set_sequence(const char* value, size_t size) {
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RequestPacketPb.sequence)
}
inline ::std::string* RequestPacketPb::mutable_sequence() {
  
  // @@protoc_insertion_point(field_mutable:RequestPacketPb.sequence)
  return sequence_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestPacketPb::release_sequence() {
  // @@protoc_insertion_point(field_release:RequestPacketPb.sequence)
  
  return sequence_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestPacketPb::set_allocated_sequence(::std::string* sequence) {
  if (sequence != NULL) {
    
  } else {
    
  }
  sequence_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sequence);
  // @@protoc_insertion_point(field_set_allocated:RequestPacketPb.sequence)
}

// int32 cmd = 3;
inline void RequestPacketPb::clear_cmd() {
  cmd_ = 0;
}
inline ::google::protobuf::int32 RequestPacketPb::cmd() const {
  // @@protoc_insertion_point(field_get:RequestPacketPb.cmd)
  return cmd_;
}
inline void RequestPacketPb::set_cmd(::google::protobuf::int32 value) {
  
  cmd_ = value;
  // @@protoc_insertion_point(field_set:RequestPacketPb.cmd)
}

// int32 subcmd = 4;
inline void RequestPacketPb::clear_subcmd() {
  subcmd_ = 0;
}
inline ::google::protobuf::int32 RequestPacketPb::subcmd() const {
  // @@protoc_insertion_point(field_get:RequestPacketPb.subcmd)
  return subcmd_;
}
inline void RequestPacketPb::set_subcmd(::google::protobuf::int32 value) {
  
  subcmd_ = value;
  // @@protoc_insertion_point(field_set:RequestPacketPb.subcmd)
}

// bytes buffer = 5;
inline void RequestPacketPb::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RequestPacketPb::buffer() const {
  // @@protoc_insertion_point(field_get:RequestPacketPb.buffer)
  return buffer_.GetNoArena();
}
inline void RequestPacketPb::set_buffer(const ::std::string& value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RequestPacketPb.buffer)
}
#if LANG_CXX11
inline void RequestPacketPb::set_buffer(::std::string&& value) {
  
  buffer_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RequestPacketPb.buffer)
}
#endif
inline void RequestPacketPb::set_buffer(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RequestPacketPb.buffer)
}
inline void RequestPacketPb::set_buffer(const void* value, size_t size) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RequestPacketPb.buffer)
}
inline ::std::string* RequestPacketPb::mutable_buffer() {
  
  // @@protoc_insertion_point(field_mutable:RequestPacketPb.buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestPacketPb::release_buffer() {
  // @@protoc_insertion_point(field_release:RequestPacketPb.buffer)
  
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestPacketPb::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    
  } else {
    
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:RequestPacketPb.buffer)
}

// map<string, string> context = 6;
inline int RequestPacketPb::context_size() const {
  return context_.size();
}
inline void RequestPacketPb::clear_context() {
  context_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
RequestPacketPb::context() const {
  // @@protoc_insertion_point(field_map:RequestPacketPb.context)
  return context_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
RequestPacketPb::mutable_context() {
  // @@protoc_insertion_point(field_mutable_map:RequestPacketPb.context)
  return context_.MutableMap();
}

// map<string, string> status = 7;
inline int RequestPacketPb::status_size() const {
  return status_.size();
}
inline void RequestPacketPb::clear_status() {
  status_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
RequestPacketPb::status() const {
  // @@protoc_insertion_point(field_map:RequestPacketPb.status)
  return status_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
RequestPacketPb::mutable_status() {
  // @@protoc_insertion_point(field_mutable_map:RequestPacketPb.status)
  return status_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ResponsePacketPb

// int32 version = 1;
inline void ResponsePacketPb::clear_version() {
  version_ = 0;
}
inline ::google::protobuf::int32 ResponsePacketPb::version() const {
  // @@protoc_insertion_point(field_get:ResponsePacketPb.version)
  return version_;
}
inline void ResponsePacketPb::set_version(::google::protobuf::int32 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:ResponsePacketPb.version)
}

// string sequence = 2;
inline void ResponsePacketPb::clear_sequence() {
  sequence_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResponsePacketPb::sequence() const {
  // @@protoc_insertion_point(field_get:ResponsePacketPb.sequence)
  return sequence_.GetNoArena();
}
inline void ResponsePacketPb::set_sequence(const ::std::string& value) {
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ResponsePacketPb.sequence)
}
#if LANG_CXX11
inline void ResponsePacketPb::set_sequence(::std::string&& value) {
  
  sequence_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ResponsePacketPb.sequence)
}
#endif
inline void ResponsePacketPb::set_sequence(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResponsePacketPb.sequence)
}
inline void ResponsePacketPb::set_sequence(const char* value, size_t size) {
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResponsePacketPb.sequence)
}
inline ::std::string* ResponsePacketPb::mutable_sequence() {
  
  // @@protoc_insertion_point(field_mutable:ResponsePacketPb.sequence)
  return sequence_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponsePacketPb::release_sequence() {
  // @@protoc_insertion_point(field_release:ResponsePacketPb.sequence)
  
  return sequence_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponsePacketPb::set_allocated_sequence(::std::string* sequence) {
  if (sequence != NULL) {
    
  } else {
    
  }
  sequence_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sequence);
  // @@protoc_insertion_point(field_set_allocated:ResponsePacketPb.sequence)
}

// int32 result = 3;
inline void ResponsePacketPb::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 ResponsePacketPb::result() const {
  // @@protoc_insertion_point(field_get:ResponsePacketPb.result)
  return result_;
}
inline void ResponsePacketPb::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:ResponsePacketPb.result)
}

// bytes buffer = 4;
inline void ResponsePacketPb::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResponsePacketPb::buffer() const {
  // @@protoc_insertion_point(field_get:ResponsePacketPb.buffer)
  return buffer_.GetNoArena();
}
inline void ResponsePacketPb::set_buffer(const ::std::string& value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ResponsePacketPb.buffer)
}
#if LANG_CXX11
inline void ResponsePacketPb::set_buffer(::std::string&& value) {
  
  buffer_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ResponsePacketPb.buffer)
}
#endif
inline void ResponsePacketPb::set_buffer(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResponsePacketPb.buffer)
}
inline void ResponsePacketPb::set_buffer(const void* value, size_t size) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResponsePacketPb.buffer)
}
inline ::std::string* ResponsePacketPb::mutable_buffer() {
  
  // @@protoc_insertion_point(field_mutable:ResponsePacketPb.buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponsePacketPb::release_buffer() {
  // @@protoc_insertion_point(field_release:ResponsePacketPb.buffer)
  
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponsePacketPb::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    
  } else {
    
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:ResponsePacketPb.buffer)
}

// map<string, string> status = 5;
inline int ResponsePacketPb::status_size() const {
  return status_.size();
}
inline void ResponsePacketPb::clear_status() {
  status_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
ResponsePacketPb::status() const {
  // @@protoc_insertion_point(field_map:ResponsePacketPb.status)
  return status_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
ResponsePacketPb::mutable_status() {
  // @@protoc_insertion_point(field_mutable_map:ResponsePacketPb.status)
  return status_.MutableMap();
}

// string msg = 6;
inline void ResponsePacketPb::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResponsePacketPb::msg() const {
  // @@protoc_insertion_point(field_get:ResponsePacketPb.msg)
  return msg_.GetNoArena();
}
inline void ResponsePacketPb::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ResponsePacketPb.msg)
}
#if LANG_CXX11
inline void ResponsePacketPb::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ResponsePacketPb.msg)
}
#endif
inline void ResponsePacketPb::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResponsePacketPb.msg)
}
inline void ResponsePacketPb::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResponsePacketPb.msg)
}
inline ::std::string* ResponsePacketPb::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:ResponsePacketPb.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponsePacketPb::release_msg() {
  // @@protoc_insertion_point(field_release:ResponsePacketPb.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponsePacketPb::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:ResponsePacketPb.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PacketVersion_Version> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PacketVersion_Version>() {
  return ::PacketVersion_Version_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Packet_2eproto__INCLUDED
